version: "3.8"

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: "always"
    networks:
      - fastapi-network

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: "always"
    ports:
      - "127.0.0.1:5555:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - fastapi-network
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "export PGPASSWORD=${DB_PASS} && psql -U ${DB_USER} -d ${DB_NAME} -h db -p ${DB_PORT} -c 'SELECT 1;'"]
      interval: 10s
      timeout: 10s
      retries: 20

networks:
  fastapi-network:
    driver: bridge
